export const SAVE_CATEGORIES = 'SAVE_CATEGORIES';

export const SAVE_ARTICLES = 'SAVE_ARTICLES';

export const SAVE_LATEST_ARTICLES = 'SAVE_LATEST_ARTICLES';

export const SAVE_SINGLE_ARTICLE = 'SAVE_SINGLE_ARTICLE';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';