export const SAVE_CATEGORIES = 'SAVE_CATEGORIES';

export const SAVE_ARTICLES = 'SAVE_ARTICLES';

export const SAVE_SINGLE_ARTICLE = 'SAVE_SINGLE_ARTICLE';

export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';

export const SAVE_USER_INFO = 'SAVE_USER_INFO'

export const REMOVE_USER_INFO = 'REMOVE_USER_INFO'

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';

export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';